Add files for ci-worker
OpenCS-ontology/OpenCS pull request #13
Opened 2023-01-21 17:05 UTC by AleksanderZawisza

Adding shacl_constraints.ttl and adding new job to the workflow.

2023-01-21 17:24 UTC, Szwagi3r commented
Also, as we wrote on teams, two different concepts (C18115, C5616) have identical prefLabel. If that was changed we could detect cycles by using sh:oneOrMorePath and recursively analyse broader concepts to compare them by prefLabels (we didn't find a way to do this directly, via IRIs) instead of manually checking if there are any concepts 9 broaders away from the focus node.

2023-01-22 07:41 UTC, Ostrzyciel commented
> Also, as we wrote on teams, two different concepts (C18115, C5616) have identical prefLabel. If that was changed we could detect cycles by using sh:oneOrMorePath and recursively analyse broader concepts to compare them by prefLabels (we didn't find a way to do this directly, via IRIs) instead of manually checking if there are any concepts 9 broaders away from the focus node.

That's an interesting find, please use the occasion to edit one of the concepts in question to resolve this. Then you can update the SHACL rule as you suggested.

2023-01-22 07:48 UTC, Ostrzyciel requested changes

2023-01-22 07:48 UTC, Ostrzyciel commented on ontology/shacl_constraints.ttl
> +    rdfs:label "Test of advanced features" ;
Test? :)

2023-01-22 07:48 UTC, Ostrzyciel commented on ontology/shacl_constraints.ttl
> +		sh:path  (skos:broader skos:broader skos:broader skos:broader skos:broader skos:broader skos:broader skos:broader skos:broader) ;
Please change this as you suggested in the PR.

2023-01-22 07:48 UTC, Ostrzyciel commented on ontology/shacl_constraints.ttl
> +		        sh:pattern "^Computer science$" ;
Why match by string? The name of the C1 concept can and will change. Can you use sh:node instead? https://www.w3.org/TR/shacl/#NodeConstraintComponent

2023-01-22 07:48 UTC, Ostrzyciel commented on ontology/shacl_constraints.ttl
> +@prefix exData: <http://datashapes.org/shasf/tests/expression/advanced.test.data#> .
I think there are some superfluous prefixes – please remove them.

2023-01-22 07:48 UTC, Ostrzyciel commented on ontology/shacl_constraints.ttl
> +<http://datashapes.org/shasf/tests/expression/advanced.test.shacl>
Please move this to some prefix that makes sense for the OpenCS ontology. Check what are the other prefixes used in OpenCS.

2023-01-22 07:48 UTC, Ostrzyciel commented on README.md
> +  - `shacl_constraints.ttl` - the file with SHACL constraints for ontology validation
```suggestion
  - `shacl_constraints.ttl` – the file with SHACL constraints for ontology validation
```

2023-01-22 07:48 UTC, Ostrzyciel commented on README.md
> +  - `shacl_constraints.ttl` - the file with SHACL constraints for ontology validation
(nitpicking: there's a tiny difference between a regular dash and an "en dash", "półpauza" in Polish)

2023-01-22 11:57 UTC, AleksanderZawisza commented
We have applied requested changes and upadated the C18115.ttl.

2023-01-22 12:01 UTC, AleksanderZawisza commented
Also, we have found another possible mistake in the ontology: C39038.ttl and C45733.ttl are the same concept (they have different labels due to misspelling). They have the same broader concept. We did not want to remove any of them yet without consultations.

2023-01-22 12:06 UTC, AleksanderZawisza commented
links for faster access:
https://github.com/OpenCS-ontology/OpenCS/blob/main/ontology/core/39/C39038.ttl
https://github.com/OpenCS-ontology/OpenCS/blob/main/ontology/core/45/C45733.ttl

2023-01-22 12:10 UTC, Ostrzyciel commented
> Also, we have found another possible mistake in the ontology: C39038.ttl and C45733.ttl are the same concept (they have different labels due to misspelling). They have the same broader concept. We did not want to remove any of them yet without consultations.

Good find! Does this break your validation somehow? If not, please just submit an issue to this repository to remove either of these.

2023-01-22 12:16 UTC, AleksanderZawisza commented
This does not break validation. We will open the issue right away.

2023-01-22 12:17 UTC, Ostrzyciel approved these changes

2023-01-22 12:18 UTC, Ostrzyciel commented
> This does not break validation. We will open the issue right away.

Perfect! Very good work then. Remember to mention what you discovered in the report (you can send me an updated version of it).

2023-01-22 12:18 UTC, merged